repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [json, yaml, markdown]

  - repo: local
    hooks:
      - id: just-fmt
        name: just --fmt
        entry: sh -c 'for file do just --fmt --justfile "$file" || exit; done' --
        language: system
        files: '(?i)(^|/)\.?justfile$|\.just$'
        types: [file]
